[tool.poetry]
name = "python_mermaid"
version = "0.1.0"
description = ""
authors = ["THIVEND <baptiste.thivend@proton.me>"]
readme = "README.md"
packages = [{include = "python_mermaid"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
