name: CI
on: pull_request

jobs:
  ci:
    strategy:
      fail-fast: false
    runs-on: ubuntu-18.04
    steps:
      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.3
      - name: Install dev dependencies
        run: poetry install --with=dev
      - name: Run flake8
        run: poetry run flake8
